/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aes;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.io.UnsupportedEncodingException;
import java.nio.charset.StandardCharsets;
import java.time.LocalTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author ducle
 */
public class AESForm extends javax.swing.JFrame {

    public static final int TYPE_HEX = 0;
    public static final int TYPE_STR = 1;
    public static final int LENGTH_TIME = 17;

    /**
     * Creates new form AESForm
     */
    public AESForm() {
        initComponents();

        //Set title icon
        Image icon = Toolkit.getDefaultToolkit().getImage(".\\icon\\AES_icon.png");
        setIconImage(icon);

        //Đặt form ra giữa
        setLocationRelativeTo(null);

        txtKey1.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateNoti1();

            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateNoti1();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateNoti1();
            }
        });

        txtKey2.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateNoti2();

            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateNoti2();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateNoti2();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbSizeKey = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtLoopNumber = new javax.swing.JTextField();
        btnThoat = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbTypeBanRo1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBanRo1 = new javax.swing.JTextArea();
        cbTypeKey1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtKey1 = new javax.swing.JTextField();
        cbTypeBanMa1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnMaHoa = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtTime1 = new javax.swing.JTextField();
        txtNotiKey1 = new javax.swing.JLabel();
        btnReset1 = new javax.swing.JButton();
        btnCopy1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtBanMa1 = new javax.swing.JTextArea();
        txtNotiBanRo1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbTypeBanMa2 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBanMa2 = new javax.swing.JTextArea();
        cbTypeKey2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtKey2 = new javax.swing.JTextField();
        cbTypeBanRo2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        btnGiaiMa = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtTime2 = new javax.swing.JTextField();
        txtNotiKey2 = new javax.swing.JLabel();
        btnReset2 = new javax.swing.JButton();
        btnCopy2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtBanRo2 = new javax.swing.JTextArea();
        txtNotiBanMa2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mã hóa và giải mã AES");
        setBackground(new java.awt.Color(102, 255, 255));
        setResizable(false);

        jPanel3.setForeground(new java.awt.Color(102, 255, 255));

        jLabel1.setText("Độ dài khóa:");

        cbSizeKey.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "128", "192", "256" }));
        cbSizeKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSizeKeyActionPerformed(evt);
            }
        });

        jLabel2.setText("Số lần lặp:");

        txtLoopNumber.setText("10");
        txtLoopNumber.setEnabled(false);

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbSizeKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLoopNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbSizeKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtLoopNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThoat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Mã hóa");

        jLabel4.setText("Bản rõ:");

        cbTypeBanRo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hex", "Chuỗi" }));

        txtBanRo1.setColumns(20);
        txtBanRo1.setLineWrap(true);
        txtBanRo1.setRows(3);
        jScrollPane1.setViewportView(txtBanRo1);

        cbTypeKey1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hex", "Chuỗi" }));

        jLabel5.setText("Khóa:");

        cbTypeBanMa1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hex", "Chuỗi" }));

        jLabel6.setText("Bản mã:");

        btnMaHoa.setText("Mã hóa");
        btnMaHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaHoaActionPerformed(evt);
            }
        });

        jLabel11.setText("Thời gian (s):");

        txtTime1.setText("00:00:00.00");
        txtTime1.setEnabled(false);

        txtNotiKey1.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        txtNotiKey1.setForeground(new java.awt.Color(255, 51, 51));
        txtNotiKey1.setText(" ");

        btnReset1.setText("Reset");
        btnReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset1ActionPerformed(evt);
            }
        });

        btnCopy1.setText("Sao chép");
        btnCopy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopy1ActionPerformed(evt);
            }
        });

        txtBanMa1.setColumns(20);
        txtBanMa1.setLineWrap(true);
        txtBanMa1.setRows(3);
        txtBanMa1.setEnabled(false);
        jScrollPane3.setViewportView(txtBanMa1);

        txtNotiBanRo1.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        txtNotiBanRo1.setForeground(new java.awt.Color(255, 51, 51));
        txtNotiBanRo1.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(868, 868, 868))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNotiBanRo1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cbTypeKey1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbTypeBanMa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNotiKey1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtKey1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbTypeBanRo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCopy1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(btnReset1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTime1)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMaHoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReset1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(cbTypeBanRo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtNotiBanRo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKey1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTypeKey1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNotiKey1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnMaHoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbTypeBanMa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCopy1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("Giải mã");

        jLabel8.setText("Bản mã:");

        cbTypeBanMa2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hex", "Chuỗi" }));

        txtBanMa2.setColumns(20);
        txtBanMa2.setLineWrap(true);
        txtBanMa2.setRows(3);
        jScrollPane2.setViewportView(txtBanMa2);

        cbTypeKey2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hex", "Chuỗi" }));

        jLabel9.setText("Khóa:");

        cbTypeBanRo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hex", "Chuỗi" }));

        jLabel10.setText("Bản rõ:");

        btnGiaiMa.setText("Giải mã");
        btnGiaiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiaiMaActionPerformed(evt);
            }
        });

        jLabel19.setText("Thời gian (s):");

        txtTime2.setText("00:00:00.00");
        txtTime2.setEnabled(false);

        txtNotiKey2.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        txtNotiKey2.setForeground(new java.awt.Color(255, 51, 51));
        txtNotiKey2.setText(" ");
        txtNotiKey2.setToolTipText("");

        btnReset2.setText("Reset");
        btnReset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset2ActionPerformed(evt);
            }
        });

        btnCopy2.setText("Sao chép");
        btnCopy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopy2ActionPerformed(evt);
            }
        });

        txtBanRo2.setColumns(20);
        txtBanRo2.setLineWrap(true);
        txtBanRo2.setRows(3);
        txtBanRo2.setEnabled(false);
        jScrollPane4.setViewportView(txtBanRo2);

        txtNotiBanMa2.setFont(new java.awt.Font("Dialog", 3, 11)); // NOI18N
        txtNotiBanMa2.setForeground(new java.awt.Color(255, 51, 51));
        txtNotiBanMa2.setText(" ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(868, 868, 868))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNotiBanMa2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbTypeBanMa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cbTypeBanRo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cbTypeKey2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(19, 19, 19)))
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNotiKey2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtKey2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCopy2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReset2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGiaiMa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTime2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(cbTypeBanMa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNotiBanMa2)
                    .addComponent(btnGiaiMa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKey2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTypeKey2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNotiKey2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbTypeBanRo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTime2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCopy2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    private void cbSizeKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSizeKeyActionPerformed
        String sizeKey = cbSizeKey.getSelectedItem().toString();
        updateNoti1();
        updateNoti2();
        switch (sizeKey) {
            case "128":
                txtLoopNumber.setText("10");
                break;
            case "192":
                txtLoopNumber.setText("12");
                break;
            case "256":
                txtLoopNumber.setText("14");
                break;
        }
    }//GEN-LAST:event_cbSizeKeyActionPerformed

    private void btnReset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset2ActionPerformed
        txtBanMa2.setText("");
        txtBanRo2.setText("");
        txtKey2.setText("");
        txtTime2.setText("00:00:00.00");
        txtNotiKey2.setText(" ");

        cbTypeBanMa2.setSelectedIndex(0);
        cbTypeBanRo2.setSelectedIndex(0);
        cbTypeKey2.setSelectedIndex(0);
    }//GEN-LAST:event_btnReset2ActionPerformed

    private void btnCopy2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopy2ActionPerformed
        StringSelection stringSelection = new StringSelection(txtBanRo2.getText());
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(stringSelection, null);
    }//GEN-LAST:event_btnCopy2ActionPerformed

    private void btnGiaiMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaiMaActionPerformed
        LocalTime timeBegin, timeEnd, timeDelay;
        timeBegin = LocalTime.now();

        int size = 0; //Kích thước khóa
        int ver = 0; //Số phiên bản

        String strOutPlaint = ""; //Chuỗi đã giải mã

        byte[] byteKey = null; //Mảng key
        int[] byteKeyExpansion; //Mảng key mở rộng

        byte[] byteInCipher = null; //Mảng byte chuyển từ chuỗi strInCipher
        byte[][][] byteInCipherConvert; //Mảng byte chuyển từ mảng byteInCipher

        size = Integer.parseInt(cbSizeKey.getSelectedItem().toString());

        AESAlgorithm aes = new AESAlgorithm(size);

        byteKey = getByte(aes, cbTypeKey2, txtKey2.getText()); //Chuyển chuỗi key thành mảng byte[]

        byteKeyExpansion = aes.createKeyExpansion(byteKey); //Tạo khóa mở rộng

        byteInCipher = getByte(aes, cbTypeBanMa2, txtBanMa2.getText()); //Chuyển chuỗi bản mã thành mảng byte[]

        ver = getVer(byteInCipher); //Xác định số phiên bản

        byteInCipherConvert = getByteInConvert(ver, byteInCipher); //Chuyển mã thành nhiều phiên bản byte[][]

        strOutPlaint = getStrOutGiaiMa(aes, ver, byteKeyExpansion, cbTypeBanRo2, byteInCipherConvert); //Chuỗi đã giải mã
        
        txtBanRo2.setText(strOutPlaint);

        timeEnd = LocalTime.now();

        timeDelay = timeEnd.minusHours(timeBegin.getHour())
                .minusMinutes(timeBegin.getMinute())
                .minusSeconds(timeBegin.getSecond())
                .minusNanos(timeBegin.getNano());

        String strTimeDelay = "" + timeDelay; //00:00:00.00000000

        if (strTimeDelay.length() <= LENGTH_TIME) {
            txtTime2.setText(strTimeDelay);
        } else {
            txtTime2.setText(strTimeDelay.substring(0, LENGTH_TIME-1));
        }
    }//GEN-LAST:event_btnGiaiMaActionPerformed

    private void btnCopy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopy1ActionPerformed
        StringSelection stringSelection = new StringSelection(txtBanMa1.getText());
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(stringSelection, null);
    }//GEN-LAST:event_btnCopy1ActionPerformed

    private void btnReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset1ActionPerformed
        txtBanMa1.setText("");
        txtBanRo1.setText("");
        txtKey1.setText("");
        txtTime1.setText("00:00:00.00");
        txtNotiKey1.setText(" ");

        cbTypeBanMa1.setSelectedIndex(0);
        cbTypeBanRo1.setSelectedIndex(0);
        cbTypeKey1.setSelectedIndex(0);
    }//GEN-LAST:event_btnReset1ActionPerformed

    private void btnMaHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaHoaActionPerformed
        LocalTime timeBegin, timeEnd, timeDelay;
        timeBegin = LocalTime.now();

        int size = 0; //Kích thước khóa
        int ver = 0; //Số phiên bản

        String strOutCipher = ""; //Chuỗi đã mã hóa

        byte[] byteKey = null; //Mảng key
        int[] byteKeyExpansion; //Mảng key mở rộng

        byte[] byteInPlaint = null; //Mảng byte chuyển từ chuỗi strInPlaint
        byte[][][] byteInPlaintConvert; //Mảng byte chuyển từ mảng byteInPlaint

        size = Integer.parseInt(cbSizeKey.getSelectedItem().toString());
        
        AESAlgorithm aes = new AESAlgorithm(size);

        byteKey = getByte(aes, cbTypeKey1, txtKey1.getText()); //Chuyển chuỗi key thành mảng byte[]
        byteKeyExpansion = aes.createKeyExpansion(byteKey); //Tạo khóa mở rộng

        byteInPlaint = getByte(aes, cbTypeBanRo1, txtBanRo1.getText()); //Chuyển chuỗi bản rõ thành mảng byte[]

        ver = getVer(byteInPlaint); //Xác định số phiên bản

        byteInPlaintConvert = getByteInConvert(ver, byteInPlaint); //Chuyển mã thành nhiều phiên bản byte[][]

        strOutCipher = getStrOutMaHoa(aes, ver, byteKeyExpansion, cbTypeBanMa1, byteInPlaintConvert); //Chuỗi đã mã hóa

        txtBanMa1.setText(strOutCipher);

        timeEnd = LocalTime.now();

        timeDelay = timeEnd.minusHours(timeBegin.getHour())
                .minusMinutes(timeBegin.getMinute())
                .minusSeconds(timeBegin.getSecond())
                .minusNanos(timeBegin.getNano());

        String strTimeDelay = "" + timeDelay; //00:00:00.00000000

        if (strTimeDelay.length() <= LENGTH_TIME) {
            txtTime1.setText(strTimeDelay);
        } else {
            txtTime1.setText(strTimeDelay.substring(0, LENGTH_TIME-1));
        }
    }//GEN-LAST:event_btnMaHoaActionPerformed

    private void updateNoti1() {
        int sizeKey = Integer.parseInt(cbSizeKey.getSelectedItem().toString());
        int lengKey = 0;

        switch (sizeKey) {
            case 128:
                lengKey = 16;
                break;
            case 192:
                lengKey = 24;
                break;
            case 256:
                lengKey = 32;
                break;
        }

        switch (cbTypeKey1.getSelectedIndex()) {
            case 0: //Hex
                if (txtKey1.getText().length() == 0) {
                    txtNotiKey1.setText(" ");
                } else if (txtKey1.getText().length() < lengKey * 2) {
                    txtNotiKey1.setText("Độ dài khóa chưa đủ");
                } else if (txtKey1.getText().length() > lengKey * 2) {
                    txtNotiKey1.setText("Độ dài khóa vượt quá");
                } else {
                    txtNotiKey1.setText(" ");
                }
                break;
            case 1: //Chuỗi
                int bytestr = 0;
                try {
                    bytestr = txtKey1.getText().getBytes("UTF-8").length;
                } catch (UnsupportedEncodingException ex) {
                    Logger.getLogger(AESForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (bytestr == 0) {
                    txtNotiKey1.setText(" ");
                } else if (bytestr < lengKey) {
                    txtNotiKey1.setText("Độ dài khóa chưa đủ");
                } else if (bytestr > lengKey) {
                    txtNotiKey1.setText("Độ dài khóa vượt quá");
                } else {
                    txtNotiKey1.setText(" ");
                }
                break;
        }
    }

    private void updateNoti2() {
        int sizeKey = Integer.parseInt(cbSizeKey.getSelectedItem().toString());
        int lengKey = 0;

        switch (sizeKey) {
            case 128:
                lengKey = 16;
                break;
            case 192:
                lengKey = 24;
                break;
            case 256:
                lengKey = 32;
                break;
        }

        switch (cbTypeKey2.getSelectedIndex()) {
            case 0: //Hex
                if (txtKey2.getText().length() == 0) {
                    txtNotiKey2.setText(" ");
                } else if (txtKey2.getText().length() < lengKey * 2) {
                    txtNotiKey2.setText("Độ dài khóa chưa đủ");
                } else if (txtKey2.getText().length() > lengKey * 2) {
                    txtNotiKey2.setText("Độ dài khóa vượt quá");
                } else {
                    txtNotiKey2.setText(" ");
                }
                break;
            case 1: //Chuỗi
                int bytestr = 0;
                try {
                    bytestr = txtKey2.getText().getBytes("UTF-8").length;
                } catch (UnsupportedEncodingException ex) {
                    Logger.getLogger(AESForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (bytestr == 0) {
                    txtNotiKey2.setText(" ");
                } else if (bytestr < lengKey) {
                    txtNotiKey2.setText("Độ dài khóa chưa đủ");
                } else if (bytestr > lengKey) {
                    txtNotiKey2.setText("Độ dài khóa vượt quá");
                } else {
                    txtNotiKey2.setText(" ");
                }
                break;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AESForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AESForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AESForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AESForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AESForm().setVisible(true);
            }
        });
    }

    private byte[] getByte(AESAlgorithm aes, JComboBox<String> cbType, String noiDung) {
        switch (cbType.getSelectedIndex()) {
            case TYPE_HEX: //Hex
                return aes.decodeHexString(noiDung); //Chuyển chuỗi Hex thành mảng Hex[]
            case TYPE_STR: //Chuoi
                try {
                return noiDung.getBytes("UTF-8"); //Chuyển chuỗi đầu vào sang byte[]
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(AESForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            break;
        }
        return null;
    }

    private int getVer(byte[] byteIn) {
        if (byteIn.length % 16 == 0) {
            return byteIn.length / 16;
        } else {
            return byteIn.length / 16 + 1;
        }
    }

    private byte[][][] getByteInConvert(int ver, byte[] byteIn) {
        byte[][][] byteInConvert = new byte[ver][4][4];
        for (int v = 0; v < ver; v++) {
            for (int i = 0; i < 4; i++) {
                for (int j = 0; j < 4; j++) {
                    if (16 * v + 4 * i + j < byteIn.length) {
                        byteInConvert[v][j][i] = byteIn[16 * v + 4 * i + j];
                    } else {
                        byteInConvert[v][j][i] = (byte) 0x20; //Thêm khoảng trống
                    }
                }
            }
        }
        return byteInConvert;
    }

    private String getStrOutMaHoa(AESAlgorithm aes, int ver, int[] byteKeyExpansion, JComboBox<String> cbType, byte[][][] byteInConvert){
        String strOut = "";
        byte[][][] byteOut = new byte[ver][4][4];
        switch (cbType.getSelectedIndex()) {
            case TYPE_HEX: //Hex
                //Mã hóa các phiên bản
                for (int v = 0; v < ver; v++) {
                    byteOut[v] = aes.cipher(byteInConvert[v], byteKeyExpansion); //Mã hóa phiên bản v
                    
                    StringBuilder sb = new StringBuilder();
                    for (int i = 0; i < 4; i++) {
                        for (int j = 0; j < 4; j++) {
                            sb.append(String.format("%02X", byteOut[v][j][i]));
                        }
                    }
                    strOut += sb.toString();
                }
                break;
            case TYPE_STR: //Chuoi
                byte[] byteOutConvert = new byte[ver * 4 * 4];
                //Mã hóa các phiên bản
                for (int v = 0; v < ver; v++) {
                    byteOut[v] = aes.cipher(byteInConvert[v], byteKeyExpansion); //Mã hóa phiên bản v
                    
                    for (int i = 0; i < 4; i++) {
                        for (int j = 0; j < 4; j++) {
                            byteOutConvert[16 * v + 4 * i + j] = byteOut[v][j][i];
                        }
                    }
                    strOut = new String(byteOutConvert, StandardCharsets.UTF_8);
                }
                break;
        }
        return strOut;
    }
    
    private String getStrOutGiaiMa(AESAlgorithm aes, int ver, int[] byteKeyExpansion, JComboBox<String> cbType, byte[][][] byteInConvert){
        String strOut = "";
        byte[][][] byteOut = new byte[ver][4][4];
        switch (cbType.getSelectedIndex()) {
            case TYPE_HEX: //Hex
                //Giải mã các phiên bản
                for (int v = 0; v < ver; v++) {
                    byteOut[v] = aes.invCipher(byteInConvert[v], byteKeyExpansion); //Mã hóa phiên bản v
                    
                    StringBuilder sb = new StringBuilder();
                    for (int i = 0; i < 4; i++) {
                        for (int j = 0; j < 4; j++) {
                            sb.append(String.format("%02X", byteOut[v][j][i]));
                        }
                    }
                    strOut += sb.toString();
                }
                break;
            case TYPE_STR: //Chuoi
                byte[] byteOutConvert = new byte[ver * 4 * 4];
                //Giải mã các phiên bản
                for (int v = 0; v < ver; v++) {
                    byteOut[v] = aes.invCipher(byteInConvert[v], byteKeyExpansion); //Mã hóa phiên bản v
                    
                    for (int i = 0; i < 4; i++) {
                        for (int j = 0; j < 4; j++) {
                            byteOutConvert[16 * v + 4 * i + j] = byteOut[v][j][i];
                        }
                    }
                    strOut = new String(byteOutConvert, StandardCharsets.UTF_8);
                }
                break;
        }
        return strOut;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCopy1;
    private javax.swing.JButton btnCopy2;
    private javax.swing.JButton btnGiaiMa;
    private javax.swing.JButton btnMaHoa;
    private javax.swing.JButton btnReset1;
    private javax.swing.JButton btnReset2;
    private javax.swing.JButton btnThoat;
    private javax.swing.JComboBox<String> cbSizeKey;
    private javax.swing.JComboBox<String> cbTypeBanMa1;
    private javax.swing.JComboBox<String> cbTypeBanMa2;
    private javax.swing.JComboBox<String> cbTypeBanRo1;
    private javax.swing.JComboBox<String> cbTypeBanRo2;
    private javax.swing.JComboBox<String> cbTypeKey1;
    private javax.swing.JComboBox<String> cbTypeKey2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea txtBanMa1;
    private javax.swing.JTextArea txtBanMa2;
    private javax.swing.JTextArea txtBanRo1;
    private javax.swing.JTextArea txtBanRo2;
    private javax.swing.JTextField txtKey1;
    private javax.swing.JTextField txtKey2;
    private javax.swing.JTextField txtLoopNumber;
    private javax.swing.JLabel txtNotiBanMa2;
    private javax.swing.JLabel txtNotiBanRo1;
    private javax.swing.JLabel txtNotiKey1;
    private javax.swing.JLabel txtNotiKey2;
    private javax.swing.JTextField txtTime1;
    private javax.swing.JTextField txtTime2;
    // End of variables declaration//GEN-END:variables
}
